### ISSUE TITLE
Tie version number in `setup-python` steps to template version number

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/copier-python#19]
For example:

```
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9                            < here
```
