### ISSUE TITLE
Implement `pyproject.toml` composition

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/copier-python#289]
One issue with having template-managed keys in `pyproject.toml` is that they have to live alongside user-specified data that is unique to any given project. The templating mechanisms available to us via Copier are powerful, but having files managed by the template while retaining user inputs is not one of its strong points. This blocks #288 and should be developed first. It would look like creating a directory `.tools/pyproject` where we keep `base.toml` and `override.toml`, and the two are merged into `./pyproject.toml`. The `base` config would be entirely managed by the template, and should contain a comment indicating to the user not to modify it. The `override` config would be populated once during project initialization in `copier-python-init`, but otherwise never touched by the template. Alternatively, depending on how key merging is handled, `copier-python-init` could also just touch the `base` config.

Either way, a script will be developed in `.tools/scripts` similar to the current `bump_pyproject.py`, which loads `base`, applies `override` on top of it, and outputs `pyproject.toml` to the root of the project directory. This also implies dependency handling, which will be tackled in a separate issue. For now, this issue will simply ingest the versions in `requirements.txt` in the same fashion as `bump_pyproject.py`.

**Comment by blakeNaccarato** [comment]
This would probably allow composing of all other requirements into extras specifications in `pyproject.toml`.

**Comment by blakeNaccarato** [comment]
Relating pinning `flit`:

> Many packages follow [Flit](https://flit.readthedocs.io/)’s recommendation and use requires = ["flit_core >=3.2,<4"] in the pyproject.toml build specification. This is reason 3 above; Flit asks you to do this. It’s also in the pyproject.toml, which by definition will never be “shared” with anything, it’s a new, disposable virtual environment that is created when building a wheel, and then thrown away, making it much more like an application requirement. However, if you only use the [PEP 621](https://www.python.org/dev/peps/pep-0621) configuration for Flit, I see no reason to cap it; this is a published standard and isn’t going to change, so Flit 4 will not “break” usage unless a bug is introduced. And Flit actually now reflects this in the version limit recommendation!

https://iscinumpy.dev/post/bound-version-constraints/

**Comment by blakeNaccarato** [comment]
For now, manually keep tooling in `.tools/pyproject.toml`. Then, devise a way to update this upon dependency bumps and such. There will need to be some passage of information to downstream jobs.

**Comment by blakeNaccarato** [comment]
Structure your `pyproject.toml` the following way.

```TOML
[project.urls]
Homepage = "..."
Documentation = "..."
Repository = "..."
Changelog = "..."
```

```TOML
[project]
name = ""
description = ""
readme = "README.md"
authors = [ { name = "", email = "" } ]
license = { file = "LICENSE" }
requires-python = ">=..."
dependencies = [ ]
keywords = ["",]
classifiers = [ "License :: OSI Approved :: MIT License", ]
```
